name: face
dependencies:
  - python=3.9
  - pip
  - pip:
      - tensorflow==2.10.0
      - keras==2.10.0
      - deepface==0.0.79
      - retina-face==0.0.13
      - opencv-python
      - numpy==1.23.5
      - kafka-python